export const phoneDisplay = "+7 700 988 5197";
export const whatsappNumber = "77009885197";
export const instagramUrl = "https://www.instagram.com/peskoblok_krg.09/";
export const whatsappDirectUrl = `https://wa.me/${whatsappNumber}`;
export const address = "г. Караганда, ул. Лесная 36";

export const categories = [
  { id: "all", label: "Все" },
  { id: "ballast", label: "Балласт" },
  { id: "otsev", label: "Отсев" },
];

export const products = [
  {
    id: "ballast-wall-gray",
    category: "ballast",
    categoryName: "Балласт",
    title: "Стеновой серый",
    price: 550,
    size: "20 x 20 x 40 см",
    image: "products-generated/ballast-wall-gray.webp",
  },
  {
    id: "ballast-wall-color",
    category: "ballast",
    categoryName: "Балласт",
    title: "Стеновой цветной",
    price: 650,
    size: "20 x 20 x 40 см",
    image: "products-generated/ballast-wall-color.webp",
  },
  {
    id: "ballast-wall-torn-gray",
    category: "ballast",
    categoryName: "Балласт",
    title: "Стеновой рваный серый",
    price: 650,
    size: "20 x 20 x 40 см",
    image: "products-generated/ballast-wall-torn-gray.webp",
  },
  {
    id: "ballast-wall-torn-color",
    category: "ballast",
    categoryName: "Балласт",
    title: "Стеновой рваный цветной",
    price: 750,
    size: "20 x 20 x 40 см",
    image: "products-generated/ballast-wall-torn-color.webp",
  },
  {
    id: "ballast-partition-gray",
    category: "ballast",
    categoryName: "Балласт",
    title: "Перегородочный серый",
    price: 450,
    size: "12 x 20 x 40 см",
    image: "products-generated/ballast-partition-gray.webp",
  },
  {
    id: "ballast-partition-color",
    category: "ballast",
    categoryName: "Балласт",
    title: "Перегородочный цветной",
    price: 550,
    size: "12 x 20 x 40 см",
    image: "products-generated/ballast-partition-color.webp",
  },
  {
    id: "ballast-partition-torn-gray",
    category: "ballast",
    categoryName: "Балласт",
    title: "Перегородочный рваный серый",
    price: 500,
    size: "9 x 20 x 40 см",
    image: "products-generated/ballast-partition-torn-gray.webp",
  },
  {
    id: "ballast-partition-torn-color",
    category: "ballast",
    categoryName: "Балласт",
    title: "Перегородочный рваный цветной",
    price: 600,
    size: "9 x 20 x 40 см",
    image: "products-generated/ballast-partition-torn-color.webp",
  },
  {
    id: "ballast-column-gray",
    category: "ballast",
    categoryName: "Балласт",
    title: "Тумба колонна серый",
    price: 1400,
    size: "32 x 32 x 20 см",
    image: "products-generated/ballast-column-gray.webp",
  },
  {
    id: "ballast-column-color",
    category: "ballast",
    categoryName: "Балласт",
    title: "Тумба колонна цветной",
    price: 1500,
    size: "32 x 32 x 20 см",
    image: "products-generated/ballast-column-color.webp",
  },
  {
    id: "ballast-parapet-gray",
    category: "ballast",
    categoryName: "Балласт",
    title: "Парапет метровый серый",
    price: 4000,
    size: "100 x 21 см",
    image: "products-generated/ballast-parapet-gray.webp",
  },
  {
    id: "ballast-cap-gray",
    category: "ballast",
    categoryName: "Балласт",
    title: "Шляпа на тумбы серый",
    price: 4000,
    size: "41 x 41 см",
    image: "products-generated/ballast-cap-gray.webp",
  },
  {
    id: "otsev-wall-gray",
    category: "otsev",
    categoryName: "Отсев",
    title: "Стеновой серый",
    price: 400,
    size: "20 x 20 x 40 см",
    image: "products-generated/otsev-wall-gray.webp",
  },
  {
    id: "otsev-wall-color",
    category: "otsev",
    categoryName: "Отсев",
    title: "Стеновой цветной",
    price: 500,
    size: "20 x 20 x 40 см",
    image: "products-generated/otsev-wall-color.webp",
  },
  {
    id: "otsev-wall-torn-gray",
    category: "otsev",
    categoryName: "Отсев",
    title: "Стеновой рваный серый",
    price: 500,
    size: "20 x 20 x 40 см",
    image: "products-generated/otsev-wall-torn-gray.webp",
  },
  {
    id: "otsev-wall-torn-color",
    category: "otsev",
    categoryName: "Отсев",
    title: "Стеновой рваный цветной",
    price: 600,
    size: "20 x 20 x 40 см",
    image: "products-generated/otsev-wall-torn-color.webp",
  },
  {
    id: "otsev-partition-gray",
    category: "otsev",
    categoryName: "Отсев",
    title: "Перегородочный серый",
    price: 350,
    size: "12 x 20 x 40 см",
    image: "products-generated/otsev-partition-gray.webp",
  },
];
